services:
  - type: web
    name: n8n-automation
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: WEBHOOK_URL
        fromService:
          name: n8n-automation
          type: web
          property: url
      - key: DB_TYPE
        value: sqlite
      - key: DB_SQLITE_PATH
        value: /data/database.sqlite
    disk:
      name: n8n-data
      mountPath: /data
      sizeGB: 1